### ISSUE TITLE
[Feature request] Share runes with friends

### ISSUE THREAD

**Issue by robinwithes** [stirante/RuneChanger#11]
**Describe the solution you'd like**
I would like a way for people to share rune pages that can be directed loaded into the runebook feature. My preferred way is a export and import button.
The export button would put data in your CTRL C buffer that the import button could then read and turn back into a local runepage. [The data could also be shared with friends who can then import it]

**Comment by stirante** [comment]
Done in https://github.com/stirante/RuneChanger/pull/14
