### ISSUE TITLE
Getting a error when picking runes

### ISSUE THREAD

**Issue by robinwithes** [stirante/RuneChanger#2]
Getting this error:
`Exception in thread "Thread-20" java.lang.NullPointerException
	at com.stirante.RuneChanger.InGameButton.lambda$null$1(InGameButton.java:127)
	at java.lang.Thread.run(Thread.java:748)`
when trying to pick recommended runes.

https://gyazo.com/6a536b533cf9e2330942566396dc3713

I am on the latest master branch.

**Comment by stirante** [comment]
Just pushed the fix :)
