### ISSUE TITLE
[Bug] After auto-updating to latest version an error occurs. "A JNI error has occurred, please check your installation and try again"

### ISSUE THREAD

**Issue by HutchMD** [stirante/RuneChanger#39]
**Describe the bug**

After automatically updating Rune Changer, an error shows when I try to launch Rune Changer.
"A JNI error has occurred, please check your installation and try again" and also "A Java Exception has occurred"

**To Reproduce**
1. Open 'RuneChanger.jar'
2. See Error mentioned above,

OR

1. Run the old 'RuneChanger.exe' (usually points to the current RuneChanger.jar')
2. See slightly different error "Class com/stirante/RuneChanger/gui/Settings not found." and then "Failed to launch JVM"

**Expected behavior**
RuneChanger would launch normally.

**Screenshots**

**(please complete the following information):**
 - OS: Windows 10 (1909)
 - RuneChanger Version [1.12.1]
 
**Additional context**

**Comment by stirante** [comment]
Are you running RuneChanger with provided scripts? (run.bat, open.bat)
If so, try running run.bat, as it should show you command line with additional information. (I know, I should've named them better)

**Comment by HutchMD** [comment]
The scripts worked, thanks!
I guess I can't use the old exe shortcut, or use the jar file now. 
I just created a shortcut to the open.bat now.

I feel there should be a little more documentation so that dummies like me don't get confused, haha!

**Comment by stirante** [comment]
Sorry, I definitely should make some kind of easy to use shortcuts.
