### ISSUE TITLE
[Bug] Unable to select RuneChanger pages in Clash

### ISSUE THREAD

**Issue by HutchMD** [stirante/RuneChanger#40]
**Describe the bug**
RuneChanger does not display the page selection button in Clash champion select.

**To Reproduce**
1. Play in Clash
2. Select your champion
3. Page Selection button is not present, so I cannot select my saved pages.

**Expected behavior**
RuneChanger functions normally and I can press the page selection button in the client.

**Screenshots**
I forgot to take screenshot... sorry

**(please complete the following information):**
 - OS: Windows 10
 - RuneChanger Version [Latest, 1.12.1?] (How do I check the version of this new format)
 
**Additional context**
I appreciate this program, and really appreciate your work. Just wanted to let you know that your program is not functioning properly in Clash.

**Comment by stirante** [comment]
Thanks for the report!

I will look into this issue this saturday.

**Comment by stirante** [comment]
Probably fixed in https://github.com/stirante/RuneChanger/commit/a88a53e4cab1a45b41592eb9b10f0bc11fbb1850

Waiting for someone to confirm, that it works
