### ISSUE TITLE
[Bug] Overlay position error

### ISSUE THREAD

**Issue by victor141516** [stirante/RuneChanger#41]
**Describe the bug**
The overlay position is far away from the LCU window.

**To Reproduce**
I'm using a 4k monitor with windows scaling set to 150%. If I change the scaling to 100% and restart RuneChanger, then it's in the correct position.

I think it's caused by how the size of the window is returned by the `getHeight` function.

**Expected behavior**
The RuneChanger overlay should be over/next to the LCU window.

**Screenshots**
![image](https://user-images.githubusercontent.com/5548950/71314676-0b5dcd80-244d-11ea-9c65-5c036dc2b820.png)

**(please complete the following information):**
 - OS: Windows 10
 - RuneChanger Version 1.12.2

**Comment by stirante** [comment]
I tried to fix it in https://github.com/stirante/RuneChanger/commit/6cc78dbb087581e2bfe681969fc630378f06063c

I also pushed changes to experimental channel, so you can check, if they're working.

**Comment by victor141516** [comment]
I works perfectly now 👍 
Thank you!
