### ISSUE TITLE
[Feature request] High Resolution Icon

### ISSUE THREAD

**Issue by maxlmuller** [stirante/RuneChanger#45]
The current icon for the app has a resolution of 32x32 pixels. It would be nice if an icon with 256x256 pixels was available. So I made an .ico file with all the used resolutions (256, 128, 96, 48, 32, 16) that will solve this issue.

Attached is the zip file with the .png and .ico file that I created.

[runechanger-runeforge-icon-256x256.zip](https://github.com/stirante/RuneChanger/files/4026290/runechanger-runeforge-icon-256x256.zip)

**Comment by stirante** [comment]
Thank you for your interest in our application. That was an issue for a while, but right now we're in the process of designing our own icon, since current one is runeforge.gg icon.

**Comment by stirante** [comment]
Finally we have our own icon :)
https://github.com/stirante/RuneChanger/blob/master/src/main/resources/images/256.png
