### ISSUE TITLE
[Bug] Enormous RAM leaks

### ISSUE THREAD

**Issue by YetiTheSmart** [stirante/RuneChanger#47]
When I first tried the app out I have noticed already concerning 0.7GB RAM usage by the process alone, then after some more time I noticed that it's eating over 2GB of RAM. Perhaps this could do some fixing? I really like the concept of this project, but sadly until the RAM leaks are fixed, I will have to draw back from using it.
Screenshot: https://prnt.sc/ragw19

Thanks in advance!

**Comment by stirante** [comment]
Have you tried the experimental version? I added there quite some performance fixes. Also I have RuneChanger running all the time on my system and never noticed it having more than 200MB of RAM.

**Comment by YetiTheSmart** [comment]
Just tried the experimental version out, didn't seem to change anything, it still memory leaks like crazy
![Untitled](https://user-images.githubusercontent.com/59294063/75806548-29687800-5d84-11ea-9d60-529375dd9d77.png)

**Comment by stirante** [comment]
The experimental version got more tweaks, that should fix high memory usage. Could you try it now?

**Comment by Adaliciously** [comment]
No response - closing for now especially that no one else is complaining about the memory usage anymore.
Feel free to reopen if you're still encountering issues.
