### ISSUE TITLE
[Feature request] How to kill this program via CLI ?, Different process name ?

### ISSUE THREAD

**Issue by Qezu** [stirante/RuneChanger#48]
Hello, I am trying to automate stuff on my computer as much as possible.
I have a script that launches your awesome program when I launch League Of Legends and I would like to also close your program when I close it. Do not worry about the launch/close detection(That is done with [Playnite](https://github.com/JosefNemec/Playnite/).

The problem is when i want to close your program via CLI(CMD or Powershell). It has same process name as any other java application. Do you have any idea how can I kill just your process ? Is there a way to launch this program with a different process name ?

Thank you

**Comment by stirante** [comment]
Hello, 
unfortunately currently there is not easy way to kill RuneChanger with CLI. Easiest I could find is with this command:
```ps
powershell.exe -Command {$pid1 = (Get-CimInstance -ClassName win32_process -Filter "commandline like '%RuneChanger%' and name like 'java%%'").Handle; Stop-Process $pid1}
```
It's searching for process, which contains RuneChanger in it's command line and with process name starting with java (depending on version, it can be java.exe or javaw.exe). After that it will save process id (field name is Handle) inside $pid1 variable ($pid is process id of current process, so we can't use it). After that we kill the process by id.

If you encounter some situations, where other apps are killed, you might want to make the filter more specific. Full command line I currently use is:
```
image/bin/javaw.exe  -cp "RuneChanger.jar;lib/*" -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" --add-exports=javafx.base/com.sun.javafx.reflect=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.javafx.scene.layout=ALL-UNNAMED com.stirante.runechanger.RuneChanger
```

In the (unspecified) future, I want to customize the java executable to replace name and icon with RuneChanger ones.

**Comment by Qezu** [comment]
Awesome
Thank you very much.
