### ISSUE TITLE
[Bug] Crash while downloading the update.

### ISSUE THREAD

**Issue by mrhappyasthma** [stirante/RuneChanger#50]
I am trying to update but keep running into this java error. I'm not sure how to resolve it.
![crash](https://user-images.githubusercontent.com/1547356/89091099-b9264880-d35b-11ea-97f6-5e77d5d4645b.JPG)

**Comment by stirante** [comment]
This looks more like you're trying to downgrade runechanger from experimental version to stable. Did you delete the settings files in the experimental version or just unchecked the experimental version in settings and restarted?

**Comment by mrhappyasthma** [comment]
That was what I was attempting. The experiment was no longer working. I just nuked my whole directory and re-downloaded. Now it's working.
