### ISSUE TITLE
[Bug] It always showing not connected! League is running.

### ISSUE THREAD

**Issue by Laezor** [stirante/RuneChanger#52]
As in the title its showing not connected no matter what I do! I will provide some screenshots and the log.

![javaw_P4nDvVY2re](https://user-images.githubusercontent.com/32393101/92292801-ab9a4a80-ef27-11ea-831b-02fd26da2ac3.png)

I get this error when I run it as an admin.

![cmd_3EV7sBC2Oh](https://user-images.githubusercontent.com/32393101/92292810-b8b73980-ef27-11ea-965d-d089ea752389.png)

**(please complete the following information):**
 - OS: [Windows 10]
 - RuneChanger Version [latest release]
 
**Additional context**
Log Information.

2020-09-05 03:20:29 [pool-1-thread-1] INFO  c.s.r.model.client.Champion - Portraits ready
2020-09-05 03:20:30 [main] INFO  com.stirante.runechanger.RuneChanger - Starting RuneChanger version 1.13.0 (master@78151b2 built at 4/2/20, 4:59 PM)
2020-09-05 03:20:30 [Thread-3] ERROR com.stirante.runechanger.RuneChanger - An unhandled exception occurred in thread Thread-3
java.lang.IllegalStateException: Couldn't find port or token in lockfile!
	at com.stirante.lolclient.ClientApi.checkClientProcess(ClientApi.java:333)
	at com.stirante.lolclient.ClientApi.lambda$startProcessWatcher$0(ClientApi.java:351)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by Adaliciously** [comment]
If you want to run it as admin, you have to tick the appropriate box in the settings.

**Comment by Laezor** [comment]
If you mean the experimental channel update. Which it does update, But still if I run it as admin I get the same error. If I open it normally its still not connected.

**Comment by Adaliciously** [comment]
> If you mean the experimental channel update. Which it does update, But still if I run it as admin I get the same error. If I open it normally its still not connected.

![image](https://user-images.githubusercontent.com/7670940/92304805-96520a00-ef81-11ea-9c1a-2872d17ab66a.png)
I'm talking about this box, you're **not** supposed to run it as an admin using the context menu (i.e. rmb->run as admin)

**Comment by Laezor** [comment]
I found that option! It runs as admin now but still is not connected.
![javaw_LIm1iq4ue9](https://user-images.githubusercontent.com/32393101/92304842-678c6180-ef8a-11ea-8661-d02a519be169.png)

**Comment by Adaliciously** [comment]
> I found that option! It runs as admin now but still is not connected.
> ![javaw_LIm1iq4ue9](https://user-images.githubusercontent.com/32393101/92304842-678c6180-ef8a-11ea-8661-d02a519be169.png)

Can you hop onto the runechanger's discord to resolve that issue? It will be much faster rather than talking through the issue

**Comment by Laezor** [comment]
Sure thing.

**Comment by Adaliciously** [comment]
Appears to be an issue with apostrophe in the executable path.

**Comment by stirante** [comment]
Fixed in https://github.com/stirante/lol-client-java-api/commit/111bfa3735401003c6fdfcaa6a6358aa7bcaa056

It will be pushed to the experimental channel soon.
