### ISSUE TITLE
Runechanger client freezes when attempting to go into settings

### ISSUE THREAD

**Issue by hmichaelkim** [stirante/RuneChanger#63]
Runechanger client freezes when attempting to go into settings

**Comment by Adaliciously** [comment]
Can you run the debug mode and show whether logs say anything?

**Comment by hmichaelkim** [comment]
I don't know why, but it's working fine now. I had rebooted earlier/force
closed the app, etc before when it was occurring too. Not sure why it's
working fine now. Sorry to bother!

**Comment by Adaliciously** [comment]
No problem. Feel free to reopen this issue if you ever encounter this kind of behavior again.
