### ISSUE TITLE
[Feature request] Aram Runes

### ISSUE THREAD

**Issue by dawidmachon** [stirante/RuneChanger#64]
Hi, any chance to add mode for ARAM? Iam only playing ARAMS, and want to be able setup app to force download runes from sites, but dedicated for arams.

**Comment by Laezor** [comment]
The metasrc data source has runes for aram. You can enable it in the settings.

**Comment by stirante** [comment]
U.gg source also downloads runes for ARAM. To enable/disable sources, go to settings, data source tab and enable/disable them.

![image](https://user-images.githubusercontent.com/2420740/100450905-c4457700-30b6-11eb-9544-a11618bf6abf.png)
