### ISSUE TITLE
Aram runes

### ISSUE THREAD

**Issue by dawidmachon** [stirante/RuneChanger#66]
There is problem with ARAM(metasrc lacking) and URUF runes, they not showing in game anymore.

**Comment by stirante** [comment]
I just checked and it works for me. Are you on the newest version?
![image](https://user-images.githubusercontent.com/2420740/109203057-fcd31a80-77a3-11eb-9f7d-57cc9505473d.png)

**Comment by dawidmachon** [comment]
You are right, on menu(app menu) runes showing up and I can save them. But in game in aram mode, not all aram related runes (not saved) showing up. metasrc always missing.

**Comment by stirante** [comment]
Ok, will check again

**Comment by stirante** [comment]
Could not reproduce, will close now.
