### ISSUE TITLE
[Bug] Exception occurred while downloading asset

### ISSUE THREAD

**Issue by i1u5** [stirante/RuneChanger#67]
**Describe the bug**
The client fails to fetch assets from cdn.communitydragon.org

**To Reproduce**
1. Run fresh install right after a new patch
2. Client will attempt to fetch assets
3. An error will show due to community dragon not being up to date, manually checking the link shows this:
`{"statusCode":404,"error":"Not Found","message":"Patch '11.6' does not exist"}`

**Expected behavior**
Client should fetch current assets properly and have previous patch version as a fallback

**Screenshots**
![image](https://user-images.githubusercontent.com/26717942/111383751-f6e89f00-86a8-11eb-97c2-eb8165d5be71.png)

**(please complete the following information):**
 - OS: Windows 10
 - RuneChanger Version 1.14.1
 
**Additional context**
The "solution" provided in expected behavior is just an idea, it could maybe be resolved in a better way, this is also not really a "bug", just an unhandled case of when the API is not up to date yet.

**Comment by stirante** [comment]
We actually have implemented fallbacks, but it seems I forgot to do this for assets, will fix it. Thanks!

**Comment by stirante** [comment]
Fixed https://github.com/stirante/RuneChanger/commit/f8e42d8b46a6de725de4e6b021808e012b1ea902
