### ISSUE TITLE
[Bug] Cannot get injected button to reliably display on LOL client

### ISSUE THREAD

**Issue by exisz** [stirante/RuneChanger#70]
Sometimes you have to open the edit rune page for the button to show.

![image](https://user-images.githubusercontent.com/38595828/124336593-f20d1400-dbe1-11eb-92ba-f89edf4bc6fc.png)
![image](https://user-images.githubusercontent.com/38595828/124336597-f5080480-dbe1-11eb-8957-c46cd4354436.png)

**Comment by stirante** [comment]
Just pushed a possible fix for that here https://github.com/stirante/RuneChanger/commit/b721fa0336070a673c629f992d1fe250cac9b6fa

Also pushed the changes to the experimental channel, which you can turn on in the RuneChanger settings. Let me know whether that fixed the bug.

**Comment by stirante** [comment]
Marking as closed due to inactivity.
