### ISSUE TITLE
[Question] Where do you get all the informations about the LoL Client ?

### ISSUE THREAD

**Issue by Vianpyro** [stirante/RuneChanger#71]
Where does all the information about the open client (player name, "auto queue", etc...) and the player's rune pages come from?

**Comment by stirante** [comment]
Everything is done using LCU API. More details on that are [here](https://developer.riotgames.com/docs/lol#league-client-api).

I specifically use my own library for that: https://github.com/stirante/lol-client-java-api

**Comment by Vianpyro** [comment]
Ok thank you :D
