### ISSUE TITLE
Avast Threat secured

### ISSUE THREAD

**Issue by belqit** [stirante/RuneChanger#80]
188.144.97.15 botnet connection detected

![image](https://user-images.githubusercontent.com/44238749/153766744-363c40a0-cf9b-46e3-96f8-99ba317210b0.png)

**Comment by stirante** [comment]
This is an information, that RuneChanger was connecting with this IP, which is on a blacklist. I looked up the IP and it belongs to CloudFlare, which is pretty much a proxy for other servers. Probably it was blindly blacklisted, when some virus used to be behind cloudflare proxy.

No RuneChanger servers use cloudflare, but some sources may use it (like u.gg or others).
